---
name: 'Setup LOLCODE'
author: Yevhen Fabizhevskyi
description: 'This action sets up a LOLCODE interpreter.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'node12'
  main: 'dist/index.js'
