---
name: CI (main)

on:
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'feature/**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Security tests
        run: yarn run security:test
      - name: Unit tests
        run: yarn run test
        if: startsWith(github.ref, 'refs/heads/bugfix/') || startsWith(github.ref, 'refs/heads/feature/')
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v2.7.4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn run test
          debug: true
  functional_tests:
    name: Functional tests
    timeout-minutes: 15
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        version: ['0.9.1', '0.9.2', '0.9.3', '0.10.1', '0.10.2', '0.10.3', '0.10.4', '0.10.5', '0.11.1', '0.11.2']
        install_cmake: [true, false]
        install_make: [true, false]
        install_lolcode: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Setup cmake
        if: ${{ matrix.install_cmake }}
        uses: symbitic/install-cmake@master
      - name: Setup make
        if: ${{ matrix.install_make }}
        uses: ouzi-dev/go-make-action@v1.5.0
      - name: Setup LOLCODE
        if: ${{ matrix.install_lolcode }}
        uses: ./
      - name: "Setup LOLCODE (skipped: ${{ matrix.install_lolcode }})"
        uses: ./
      - name: Run script (Linux, MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: lci ./hello-world.lc
      - name: Run script (Windows)
        if: matrix.os == 'windows-latest'
        run: lci.exe ./hello-world.lc
